[package]
name = "nyse-logos"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
colog = "1.3.0"
log = "0.4.22"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
